[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 2
optimizer = true
optimizer-runs = 500
solc_version = '0.8.20'
evm_version = 'paris'

[profile.openzeppelin]
ast = true
build_info = true
extra_output = ["storageLayout"]
ffi = true
fs_permissions = [{ access = 'read-write', path = './'}]

[fuzz]
runs = 15_000
fail_on_revert = true

[rpc_endpoints]
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
baseSepolia = { key = "${BASE_ETHERSCAN_API_KEY}" }
base = { key = "${BASE_ETHERSCAN_API_KEY}" }

[doc]
title = "Flat Money V1"

[profile.ci.fuzz]
runs = 1_000
fail_on_revert = true

[profile.deepci.fuzz]
runs = 25_000
fail_on_revert = true
